const playersChoices = [
  {
    level: 44,
    maxHealth: 177,
    name: 'Morty',
    img: require('../assets/morty.png'),
    magic: 52,
    attack: 30,
    defense: 10,
    magicDefense: 30,
  },
  {
    level: 44,
    name: 'Rick',
    maxHealth: 188,
    img: require('../assets/rick.png'),
    magic: 30,
    attack: 52,
    defense: 30,
    magicDefense: 48,
  },
  {
    level: 35,
    name: 'Summer',
    maxHealth: 150,
    img: require('../assets/summer.png'),
    magic: 20,
    attack: 25,
    defense: 40,
    magicDefense: 50,
  },
  {
    level: 10,
    name: 'Jerry',
    maxHealth: 100,
    img: require('../assets/jerry.png'),
    magic: 10,
    attack: 10,
    defense: 15,
    magicDefense: 15,
  },
  {
    level: 47,
    name: 'Squanchy',
    maxHealth: 200,
    img: require('../assets/squanchy.png'),
    magic: 60,
    attack: 50,
    defense: 15,
    magicDefense: 60,
  },
  {
    level: 43,
    name: 'Persuccello',
    maxHealth: 190,
    img: require('../assets/birdperson.png'),
    magic: 60,
    attack: 40,
    defense: 20,
    magicDefense: 30,
  },
  {
    level: 40,
    name: 'Mr.Miguardi',
    maxHealth: 180,
    img: require('../assets/MrMeeseeks.png'),
    magic: 60,
    attack: 40,
    defense: 20,
    magicDefense: 30,
  },
];

const opponentsChoices = [
  {
    level: 44,
    name: 'Rick',
    maxHealth: 188,
    img: require('../assets/rick.png'),
    magic: 30,
    attack: 52,
    defense: 30,
    magicDefense: 48,
  },
  {
    level: 38,
    name: 'Morty Malvagio',
    maxHealth: 177,
    img: require('../assets/MortyEvil.png'),
    magic: 40,
    attack: 30,
    defense: 20,
    magicDefense: 30,
  },
  {
    level: 39,
    name: 'Rick Malvagio',
    maxHealth: 188,
    img: require('../assets/Evil_Rick.png'),
    magic: 60,
    attack: 30,
    defense: 20,
    magicDefense: 30,
  },
];
export const playerStats =
  playersChoices[Math.floor(Math.random() * playersChoices.length)];

export const opponentStats =
  opponentsChoices[Math.floor(Math.random() * opponentsChoices.length)];
