export const characters = [
  {
    level: 44,
    maxHealth: 177,
    name: 'Morty',
    img: require('../../assets/morty-select.png'),
    magic: 52,
    attack: 30,
    defense: 10,
    magicDefense: 30,
  },
  {
    level: 44,
    name: 'Rick',
    maxHealth: 188,
    img: require('../../assets/rick.png'),
    magic: 30,
    attack: 52,
    defense: 30,
    magicDefense: 48,
  },
  {
    level: 44,
    name: 'Summer',
    maxHealth: 150,
    img: require('../../assets/summer.png'),
    magic: 20,
    attack: 25,
    defense: 40,
    magicDefense: 50,
  },
  {
    level: 44,
    name: 'Jerry',
    maxHealth: 100,
    img: require('../../assets/jerry.png'),
    magic: 5,
    attack: 5,
    defense: 10,
    magicDefense: 5,
  },
  {
    level: 44,
    name: 'Squanchy',
    maxHealth: 160,
    img: require('../../assets/squanchy.png'),
    magic: 50,
    attack: 40,
    defense: 15,
    magicDefense: 60,
  },
  {
    level: 44,
    name: 'Persuccello',
    maxHealth: 177,
    img: require('../../assets/birdperson.png'),
    magic: 60,
    attack: 40,
    defense: 20,
    magicDefense: 30,
  },
  {
    level: 44,
    name: 'Mr.Miguardi',
    maxHealth: 177,
    img: require('../../assets/MrMeeseeks.png'),
    magic: 60,
    attack: 40,
    defense: 20,
    magicDefense: 30,
  },
];
